CODE
; Configura PORT A como saida (TRIS A = 0)
    ORG	    0x00
    BCF	    0x03, 0x05	; STATUS RP0 = 0
    CLRF    0x05	; LIMPA PORT A
    
    BSF	    0x03, 0x05	; STATUS RP0 = 1 
    MOVLW   0x00	; MOVE 0 PARA W
    MOVWF   0x05	; MOVE W PARA F 0x05

; Configura PORT B como entrada (TRIS B = 1)
    BCF	    0x03, 0x05	; STATUS RP0 = 0
    CLRF    0x06	; LIMPA PORT B
    
    BSF	    0x03, 0x05	; STATUS RP0 = 1
    MOVLW   0xFF	; MOVE 255 PARA W
    MOVWF   0x06	; MOVE W PARA F 0x06
    
    BCF	    0x03, 0x05  ; STATUS RP0 = 0
    
MAIN_LOOP:
    MOVLW   0x00	; LIMPA W
    ADDWF   0x05, 0x00	; MOVE PORTA PARA W
    MOVWF   0x0D	; SETA O BUFFER DE SAIDA
    MOVLW   0x00	; LIMPA W
    ADDWF   0x06, 0x00	; MOVE PORTB PARA W
    MOVWF   0x0C	; SALVA ENTRADA NA MEMORIA
    
    BTFSC   0x0C, 0x00	; VERIFICA SE O BOTÃO DE TRANCAR A PORTA 1 FOI APERTADO
    CALL    TRANCA_PORTA; TRANCA A PORTA 1

    BTFSC   0x0C, 0x01	; VERIFICA SE O BOTÃO DE TRANCAR A PORTA 2 FOI APERTADO
    CALL    TRANCA_PORTB; TRANCA A PORTA 2
    
    BTFSC   0x0C, 0x04	; VERIFICA SE O BOTÃO DO MOTORISTA FOI APERTADO
    CALL    TROCA_PORT	; TROCA O ESTADO DAS PORTAS
    
    MOVLW   0x04	; MOVE 0100b PARA W
    BTFSS   0x0D, 0x02	; VERIFICA SE O SINAL JÁ ESTA ATIVO
    ADDWF   0x0D, 0x01	; ATIVA O SINAL SONORO
    MOVLW   0x0B	; MOVE 1011b PARA W
    BTFSS   0x0C, 0x02	; VERIFICA SE A PORTA 1 ESTA TRANCADA
    MOVLW   0x0F
    BTFSS   0x0C, 0x03	; VERIFICA SE A OIRTA 2 ESTA TRANCADA
    MOVLW   0x0F
    ANDWF   0x0D, 0x01	; CORRIGE O SINAL DO ALARME PARA O BUFFER DE SAIDA
    
    MOVLW   0x00	; LIMPA W
    ADDWF   0x0D, 0x00	; MOVE O BUFFER DE SAIDA PARA W
    MOVWF   0x05	; MANDA O SINAL PARA AS PORTAS
    GOTO    MAIN_LOOP
    
TRANCA_PORTA:
    MOVLW   0x00	; LIMPA W
    BTFSS   0x0C, 0x02	; VERIFICA SE A PORTA A JÁ ESTAVA TRANCADA
    MOVLW   0x01	; SE NÃO ADICIONA O SINAL DE TRANCAR
    ADDWF   0x0D, 0x01	; MOVE O SINAL ESCOLHIDO PRO BUFFER DE SAIDA
    RETURN
    
TRANCA_PORTB:
    MOVLW   0x00	; LIMPA W
    BTFSS   0x0C, 0x03	; VERIFICA SE A PORTA B JÁ ESTAVA TRANCADA
    MOVLW   0x02	; SE NÃO ADICIONA O SINAL DE TRANCAR
    ADDWF   0x0D, 0x01	; MOVE O SINAL ESCOLHIDO PRO BUFFER DE SAIDA
    RETURN
    
TROCA_PORT:
    BTFSC   0x0C, 0x05	; VERIFICA SE O CARRO ESTA ACIMA DE 20KM/H
    GOTO    VELOCIDADE	; VAI PARA O CODIGO DE TRANCAR 
    MOVLW   0x03	; MOVE 11b PARA W
    XORWF   0x0D, 0x01	; TROCA OS SINAIS DAS PORTAS NO BUFFER DE SAIDA
    RETURN
VELOCIDADE:
    CALL    TRANCA_PORTA; TRANCA PORTA 1
    CALL    TRANCA_PORTB; TRANCA PORTA 2
    RETURN
    
END